backstage = false
checkssh = true
cloudinarycloudname = 'dlwdq84ig'
configdirectory = 'C:\Users\sai.banda\Desktop\new-ct\CT_FRONTEND_PROJECT\.frontastic'
customername = 'demo'
customtasticsroot = ''
filesync = false
https = true
ismultitenant = false
lastversioncheck = '2024-02-12 17:12:05.7016469 +0530 IST'
latestversion = '2.3.1'
projectname = 'english'
projectroot = 'C:\Users\sai.banda\Desktop\new-ct\CT_FRONTEND_PROJECT'
remoteserverhostname = 'english-demo.frontastic.io'
studioapiusertoken = ''
studiouseremail = 'dev@frontastic.io'
syncfrontend = false
traefikdashboardconfigpath = 'C:\Users\sai.banda\Desktop\new-ct\CT_FRONTEND_PROJECT\.frontastic\traefik_config\dashboard.toml'
traefikssrconfigpath = 'C:\Users\sai.banda\Desktop\new-ct\CT_FRONTEND_PROJECT\.frontastic\traefik_config\ssr.toml'
traefikwebpackconfigpath = 'C:\Users\sai.banda\Desktop\new-ct\CT_FRONTEND_PROJECT\.frontastic\traefik_config\webpack.toml'
